### PR TITLE
Add possibility to request dependency on every property call

### PR DESCRIPTION
**Pull request by kirich1409**
Need to have possibility to inject every time new instance of dependency. Now library only has possibility to inject dependency lazy via `inject`. My PR add functional similar to Java JSR-330 [Provider](https://docs.oracle.com/javaee/6/api/javax/inject/Provider.html).

### CODE REVIEW

**Comment by arnaudgiuliani** [comment]
Hello,

I don't understand well the need behind that. Can you give me a complete use case to illustrate that?

`factory` declaration and dynamic parameters allow you to better shape your injection.

**Comment by kirich1409** [comment]
Problem is that inject this is lazy get of dependency and it will not change until object will be destroyed. But in some cases a need to create every time new dependency instance with `factory` declaration.

Case when I need this: I have data `Repository` (_bean_) that contains functions to execute `Request` (_factory_). Every `Request` is special class that encapsulate logic of caching, error handling and other. On every request it has own dependencies. In current implementation only possibility is to create instance of `Request` inside `Repository`

**Comment by arnaudgiuliani** [comment]
I think that you could use a factory provider:

`factory { create your `Request` }`

You can also use dynamic parameters to be use when injecting it:

`factory{ params -> makeRequest(params['a_param'])}`
`val request : by inject { mapOf('a_param' to <givenValue>) }`

It is a particular factory usage?

**Comment by kirich1409** [comment]
Why `inject` is lazy? I don't understand this case when I started to work with Koin, that why I have problem and need simple case to work with `factory` declaration as expected. `inject` cache value no matter is this dependency declared as `bean` or `factory`.

**Comment by kirich1409** [comment]
```kotlin
class TeacherRepository : KoinComponent {
    // Every call request dependency. NetworkBoundResource declaraed as factory
    private val networkBoundResource: NetworkBoundResource<List<TeacherDbo>, Items<TeacherDto>>
            by provider(NetworkBoundResources.TEACHERS)

    fun loadTeachers(force: Boolean = false): LiveData<Resource<List<TeacherDbo>>> {
        return with(networkBoundResource) {
            load(force)
            asLiveData()
        }
    }
}
```

**Pull request closed without merging**
