### PR TITLE
Add possibility to get dependency from Android Component

### PR DESCRIPTION
**Pull request by kirich1409**
Add possibility to get dependency from Android Components without inject it

### CODE REVIEW

**Comment by arnaudgiuliani** [comment]
Hello,

you mean to have the `get()` eager injection function into Android components. 

I push the semantic on the `by inject()` style lazy properties declaration. But why not unlock the `get()` function. But I think that most cases can be declared with lazy property injection. The `get()` function should be used to inject a dependency on a local/short function.

**Comment by kirich1409** [comment]
In some case i need dependency to only execute single operation and no need a property. Simple case from Android: main Activity of app check state from preference (that is dependency in Koin) and after this start another screen based on preference value.

**Comment by kirich1409** [comment]
This possibility is analogue of method injection from Dagger 2.

**Comment by arnaudgiuliani** [comment]
Ok

**Comment by arnaudgiuliani** [comment]
Please check conflicts

**Comment by arnaudgiuliani** [comment]
I already added the fix - https://github.com/Ekito/koin/commit/789c95fba360057bcd23e6c04045295543de4c91

**Pull request closed without merging**
