### PR TITLE
Koin android architecture lazy inject

### PR DESCRIPTION
**Pull request by fredy-mederos**
This request is to archive the following feature:
```
// Bind it to your Activity
val viewModel by injectViewModel<MyViewModel>()

class MyActivity() : AppCompatActivity() {
  override fun onCreate(){
    super.onCreate()
    viewModel.someFunction()
  }
}
```

### CODE REVIEW

**Comment by arnaudgiuliani** [comment]
I would add some improvements on how write the lazy delegate, directly reuse the getViewModel() function

**Comment by fredy-mederos** [comment]
You are right! I did it in my project but I forget to commit it in the fork

**Comment by arnaudgiuliani** [comment]
I will provide an update for lazy get viewModel and fragment integration. Once available on 0.8.1 I will notice you to check it.

**Comment by arnaudgiuliani** [comment]
Not sure if you reuse the same ViewModel with several fragments, you intend to reuse the same instance. Else you use separated ViewModel. This makes things simple to understand.

For now, I think to propose shared viewmodel only. We will see if there's need for recreating the same viewmodel instance for fragment

**Comment by fredy-mederos** [comment]
So I can remove the `shareWithActivityViewModel: Boolean` param and always use the `ViewModelStores.of(activity)` to use the shared viewmodel only

**Comment by arnaudgiuliani** [comment]
I suggest a default parameter to always get VM from activity, and allow to create a new one if needed.

I will merge your code and notify you for an alpha version of koin to check.

Stay tunned!

**Comment by fredy-mederos** [comment]
Ok thanks!

**Comment by arnaudgiuliani** [comment]
Check the 0.8.1-alpha-7 👍

**Pull request closed without merging**
