### PR TITLE
Feature/java availability

### PR DESCRIPTION
**Pull request by fredy-mederos**
Including an utility class to easily obtain koin components and properties from java code. 
There was also added some test files to validate the features.

### CODE REVIEW

**Comment by arnaudgiuliani** [comment]
Hello, we will begin to check that for `1.0.0`. Stay in touch

**Comment by arnaudgiuliani** [comment]
Hello @fredy-mederos, I will prepare a dedicated `koin-java` module to isolate this static helper.
Stay tuned

**Comment by arnaudgiuliani** [comment]
@fredy-mederos can you move your files into `koin-java` project?

**Comment by fredy-mederos** [comment]
Yes I will do it in a few minutes.

**Comment by fredy-mederos** [comment]
I will run the test cases. Wait for my confirmation to merge.

**Comment by fredy-mederos** [comment]
All test passed!

**Pull request merged**
